// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionArchitectureWebAPI.Persistance.Context;

#nullable disable

namespace OnionArchitectureWebAPI.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125220622_mig2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(7444),
                            IsDeleted = false,
                            Name = "Egeli - Arslanoğlu"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(7622),
                            IsDeleted = false,
                            Name = "Evliyaoğlu and Sons"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(7727),
                            IsDeleted = false,
                            Name = "Avan Inc"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(7833),
                            IsDeleted = false,
                            Name = "Menemencioğlu Inc"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(7921),
                            IsDeleted = false,
                            Name = "Akan Group"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8018),
                            IsDeleted = false,
                            Name = "Kulaksızoğlu Inc"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8107),
                            IsDeleted = false,
                            Name = "Kumcuoğlu - Nalbantoğlu"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8198),
                            IsDeleted = false,
                            Name = "Uluhan - Eronat"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8280),
                            IsDeleted = false,
                            Name = "Akan - Arslanoğlu"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8379),
                            IsDeleted = false,
                            Name = "Atakol LLC"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8521),
                            IsDeleted = true,
                            Name = "Okumuş, Erbay and Koç"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8657),
                            IsDeleted = true,
                            Name = "Gönültaş, Kılıççı and Akar "
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8793),
                            IsDeleted = true,
                            Name = "Çevik, Aybar and Balaban"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8878),
                            IsDeleted = true,
                            Name = "Babaoğlu - Polat"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 516, DateTimeKind.Local).AddTicks(8970),
                            IsDeleted = true,
                            Name = "Yeşilkaya - Özkara"
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priorty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 517, DateTimeKind.Local).AddTicks(2877),
                            IsDeleted = false,
                            Name = "Elektrik",
                            ParentId = 0,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 517, DateTimeKind.Local).AddTicks(2888),
                            IsDeleted = false,
                            Name = "Moda",
                            ParentId = 0,
                            Priorty = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 517, DateTimeKind.Local).AddTicks(2889),
                            IsDeleted = false,
                            Name = "Bilgisayar",
                            ParentId = 1,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 517, DateTimeKind.Local).AddTicks(2891),
                            IsDeleted = false,
                            Name = "Kadın",
                            ParentId = 2,
                            Priorty = 1
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3177),
                            Description = "Voluptate inventore ut gidecekmiş ut.",
                            IsDeleted = false,
                            Title = "Dağılımı."
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3263),
                            Description = "İncidunt sarmal qui iusto praesentium.",
                            IsDeleted = false,
                            Title = "Bahar."
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3335),
                            Description = "Göze masanın eos türemiş değerli.",
                            IsDeleted = false,
                            Title = "Salladı."
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3411),
                            Description = "Kapının quis non oldular cesurca.",
                            IsDeleted = false,
                            Title = "De."
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3474),
                            Description = "Voluptatem bundan voluptas incidunt ve.",
                            IsDeleted = false,
                            Title = "Ea."
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3532),
                            Description = "Velit öyle rem olduğu suscipit.",
                            IsDeleted = false,
                            Title = "Orta."
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3593),
                            Description = "Dergi de adipisci qui çünkü.",
                            IsDeleted = false,
                            Title = "Ea."
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3655),
                            Description = "Ötekinden okuma layıkıyla yapacakmış laudantium.",
                            IsDeleted = false,
                            Title = "Eos."
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3717),
                            Description = "Çıktılar aperiam un göze dicta.",
                            IsDeleted = false,
                            Title = "Dağılımı."
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3775),
                            Description = "Ona odit umut consequatur rem.",
                            IsDeleted = false,
                            Title = "Telefonu."
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3849),
                            Description = "Voluptatem düşünüyor çakıl eos reprehenderit.",
                            IsDeleted = false,
                            Title = "Magnam."
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3906),
                            Description = "Sit ona adipisci voluptas architecto.",
                            IsDeleted = false,
                            Title = "Çıktılar."
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(3964),
                            Description = "Ötekinden dolore beğendim sıla qui.",
                            IsDeleted = false,
                            Title = "Adresini."
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(4025),
                            Description = "Gazete fugit mi odio düşünüyor.",
                            IsDeleted = false,
                            Title = "Kalemi."
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(4087),
                            Description = "Ab sunt qui koyun ab.",
                            IsDeleted = false,
                            Title = "İpsa."
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(4142),
                            Description = "Bilgiyasayarı umut olduğu camisi et.",
                            IsDeleted = false,
                            Title = "İllo."
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(4199),
                            Description = "Gördüm çakıl dignissimos cesurca ona.",
                            IsDeleted = false,
                            Title = "Ex."
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(4688),
                            Description = "Sunt quis magnam illo totam.",
                            IsDeleted = false,
                            Title = "Masanın."
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(4756),
                            Description = "Aut dışarı sokaklarda dağılımı et.",
                            IsDeleted = false,
                            Title = "Çıktılar."
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(4812),
                            Description = "Dışarı ışık sıfat nesciunt sokaklarda.",
                            IsDeleted = false,
                            Title = "Architecto."
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(4880),
                            Description = "Salladı quae autem ea eos.",
                            IsDeleted = true,
                            Title = "Açılmadan."
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(4943),
                            Description = "Consequatur oldular ea architecto dergi.",
                            IsDeleted = true,
                            Title = "Qui."
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(5007),
                            Description = "Orta beatae vel rem quia.",
                            IsDeleted = true,
                            Title = "Ad."
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(5061),
                            Description = "Masanın voluptas inventore exercitationem ut.",
                            IsDeleted = true,
                            Title = "Velit."
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 520, DateTimeKind.Local).AddTicks(5103),
                            Description = "Quis kulu gördüm mutlu uzattı.",
                            IsDeleted = true,
                            Title = "Voluptatem."
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1129),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 13.27m,
                            IsDeleted = false,
                            Price = 5033.13m,
                            Title = "Tasty Fresh Bacon"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1188),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 16.07m,
                            IsDeleted = false,
                            Price = 8876.45m,
                            Title = "Unbranded Concrete Fish"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1240),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 38.85m,
                            IsDeleted = false,
                            Price = 5662.97m,
                            Title = "Gorgeous Wooden Bike"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1277),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 15.33m,
                            IsDeleted = false,
                            Price = 3700.08m,
                            Title = "Handcrafted Concrete Cheese"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1313),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 8.74m,
                            IsDeleted = false,
                            Price = 3228.39m,
                            Title = "Fantastic Cotton Computer"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1348),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 28.47m,
                            IsDeleted = false,
                            Price = 8578.14m,
                            Title = "Intelligent Granite Bike"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1384),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 46.99m,
                            IsDeleted = false,
                            Price = 9081.34m,
                            Title = "Incredible Cotton Mouse"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1421),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 3.58m,
                            IsDeleted = false,
                            Price = 6068.32m,
                            Title = "Fantastic Wooden Tuna"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1456),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 2.29m,
                            IsDeleted = false,
                            Price = 4151.16m,
                            Title = "Small Frozen Bike"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1491),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 24.42m,
                            IsDeleted = false,
                            Price = 1866.48m,
                            Title = "Unbranded Wooden Mouse"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1525),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 46.33m,
                            IsDeleted = false,
                            Price = 6143.50m,
                            Title = "Tasty Fresh Tuna"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1571),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 45.14m,
                            IsDeleted = false,
                            Price = 9170.02m,
                            Title = "Unbranded Wooden Tuna"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1604),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 12.06m,
                            IsDeleted = false,
                            Price = 9798.31m,
                            Title = "Intelligent Wooden Tuna"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1638),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 8.27m,
                            IsDeleted = false,
                            Price = 4004.49m,
                            Title = "Refined Fresh Chair"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1671),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 20.33m,
                            IsDeleted = false,
                            Price = 5391.53m,
                            Title = "Gorgeous Concrete Salad"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1706),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 2.18m,
                            IsDeleted = false,
                            Price = 8218.79m,
                            Title = "Handcrafted Wooden Tuna"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1740),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 25.17m,
                            IsDeleted = false,
                            Price = 8583.35m,
                            Title = "Ergonomic Fresh Tuna"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1774),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 5.00m,
                            IsDeleted = false,
                            Price = 9384.92m,
                            Title = "Handcrafted Plastic Computer"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1810),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 0.34m,
                            IsDeleted = false,
                            Price = 6418.85m,
                            Title = "Unbranded Concrete Shirt"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1844),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 46.60m,
                            IsDeleted = false,
                            Price = 6620.96m,
                            Title = "Unbranded Plastic Bacon"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1879),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 41.95m,
                            IsDeleted = false,
                            Price = 780.47m,
                            Title = "Licensed Fresh Keyboard"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1925),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 22.30m,
                            IsDeleted = false,
                            Price = 7576.57m,
                            Title = "Small Metal Soap"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1960),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 16.00m,
                            IsDeleted = false,
                            Price = 6429.51m,
                            Title = "Practical Frozen Table"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(1993),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 22.32m,
                            IsDeleted = false,
                            Price = 2133.76m,
                            Title = "Awesome Plastic Salad"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2026),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 34.43m,
                            IsDeleted = false,
                            Price = 8614.59m,
                            Title = "Gorgeous Steel Chair"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2059),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 18.51m,
                            IsDeleted = false,
                            Price = 7472.73m,
                            Title = "Licensed Concrete Chicken"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2092),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 25.64m,
                            IsDeleted = false,
                            Price = 9640.92m,
                            Title = "Rustic Soft Computer"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2126),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 4.13m,
                            IsDeleted = false,
                            Price = 741.03m,
                            Title = "Fantastic Steel Shirt"
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2159),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 49.99m,
                            IsDeleted = false,
                            Price = 4136.97m,
                            Title = "Awesome Cotton Pizza"
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2193),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 8.75m,
                            IsDeleted = false,
                            Price = 6195.96m,
                            Title = "Awesome Granite Bacon"
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2239),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 30.05m,
                            IsDeleted = false,
                            Price = 6296.69m,
                            Title = "Awesome Metal Gloves"
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2273),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 38.26m,
                            IsDeleted = false,
                            Price = 2092.96m,
                            Title = "Unbranded Steel Ball"
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2306),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 25.34m,
                            IsDeleted = false,
                            Price = 6624.55m,
                            Title = "Practical Rubber Shoes"
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2339),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 46.22m,
                            IsDeleted = false,
                            Price = 5258.13m,
                            Title = "Tasty Cotton Fish"
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2373),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 23.08m,
                            IsDeleted = false,
                            Price = 1465.43m,
                            Title = "Incredible Plastic Chicken"
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2407),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 20.84m,
                            IsDeleted = false,
                            Price = 9697.79m,
                            Title = "Handmade Soft Sausages"
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2441),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 39.33m,
                            IsDeleted = false,
                            Price = 8672.29m,
                            Title = "Practical Frozen Pizza"
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2475),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 1.19m,
                            IsDeleted = false,
                            Price = 8466.85m,
                            Title = "Practical Fresh Pants"
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2509),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 0.77m,
                            IsDeleted = false,
                            Price = 2550.05m,
                            Title = "Tasty Rubber Ball"
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2542),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 0.41m,
                            IsDeleted = false,
                            Price = 1842.95m,
                            Title = "Gorgeous Wooden Bike"
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2585),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 30.27m,
                            IsDeleted = false,
                            Price = 6442.15m,
                            Title = "Intelligent Granite Chips"
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2619),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 28.65m,
                            IsDeleted = false,
                            Price = 5153.07m,
                            Title = "Unbranded Cotton Keyboard"
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2652),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 49.32m,
                            IsDeleted = false,
                            Price = 6925.20m,
                            Title = "Sleek Fresh Chicken"
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2686),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 34.92m,
                            IsDeleted = false,
                            Price = 3775.50m,
                            Title = "Unbranded Fresh Bike"
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2719),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 6.54m,
                            IsDeleted = false,
                            Price = 998.76m,
                            Title = "Tasty Plastic Table"
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2752),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 43.43m,
                            IsDeleted = false,
                            Price = 5625.60m,
                            Title = "Licensed Cotton Shirt"
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2785),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 9.95m,
                            IsDeleted = false,
                            Price = 8031.14m,
                            Title = "Handmade Rubber Hat"
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2819),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 15.27m,
                            IsDeleted = false,
                            Price = 7715.62m,
                            Title = "Intelligent Concrete Shoes"
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2853),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 41.55m,
                            IsDeleted = false,
                            Price = 8276.12m,
                            Title = "Fantastic Wooden Pizza"
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2894),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 31.45m,
                            IsDeleted = false,
                            Price = 5691.62m,
                            Title = "Tasty Metal Bacon"
                        },
                        new
                        {
                            Id = 51,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2938),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 21.63m,
                            IsDeleted = true,
                            Price = 6782.45m,
                            Title = "Refined Rubber Hat"
                        },
                        new
                        {
                            Id = 52,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(2973),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 1.16m,
                            IsDeleted = true,
                            Price = 8257.92m,
                            Title = "Handmade Soft Sausages"
                        },
                        new
                        {
                            Id = 53,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3007),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 28.04m,
                            IsDeleted = true,
                            Price = 8901.74m,
                            Title = "Sleek Wooden Ball"
                        },
                        new
                        {
                            Id = 54,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3041),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 49.66m,
                            IsDeleted = true,
                            Price = 8265.99m,
                            Title = "Handmade Rubber Pizza"
                        },
                        new
                        {
                            Id = 55,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3076),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 24.39m,
                            IsDeleted = true,
                            Price = 333.47m,
                            Title = "Handcrafted Frozen Sausages"
                        },
                        new
                        {
                            Id = 56,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3109),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 16.22m,
                            IsDeleted = true,
                            Price = 9766.33m,
                            Title = "Awesome Plastic Soap"
                        },
                        new
                        {
                            Id = 57,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3143),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 38.43m,
                            IsDeleted = true,
                            Price = 6597.19m,
                            Title = "Handmade Frozen Bacon"
                        },
                        new
                        {
                            Id = 58,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3177),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 10.98m,
                            IsDeleted = true,
                            Price = 2885.69m,
                            Title = "Tasty Rubber Cheese"
                        },
                        new
                        {
                            Id = 59,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3224),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 27.94m,
                            IsDeleted = true,
                            Price = 1808.52m,
                            Title = "Ergonomic Metal Hat"
                        },
                        new
                        {
                            Id = 60,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3258),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 49.14m,
                            IsDeleted = true,
                            Price = 2644.40m,
                            Title = "Refined Steel Tuna"
                        },
                        new
                        {
                            Id = 61,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3291),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 46.53m,
                            IsDeleted = true,
                            Price = 6394.29m,
                            Title = "Practical Soft Hat"
                        },
                        new
                        {
                            Id = 62,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3325),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 3.47m,
                            IsDeleted = true,
                            Price = 8199.60m,
                            Title = "Handcrafted Fresh Mouse"
                        },
                        new
                        {
                            Id = 63,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3358),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 46.91m,
                            IsDeleted = true,
                            Price = 5282.04m,
                            Title = "Practical Rubber Pizza"
                        },
                        new
                        {
                            Id = 64,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3392),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 10.35m,
                            IsDeleted = true,
                            Price = 383.70m,
                            Title = "Gorgeous Rubber Chair"
                        },
                        new
                        {
                            Id = 65,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3425),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 20.70m,
                            IsDeleted = true,
                            Price = 1837.37m,
                            Title = "Intelligent Concrete Table"
                        },
                        new
                        {
                            Id = 66,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3459),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 9.76m,
                            IsDeleted = true,
                            Price = 6355.28m,
                            Title = "Sleek Steel Shirt"
                        },
                        new
                        {
                            Id = 67,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3492),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 13.43m,
                            IsDeleted = true,
                            Price = 7323.30m,
                            Title = "Handmade Plastic Gloves"
                        },
                        new
                        {
                            Id = 68,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3525),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 25.82m,
                            IsDeleted = true,
                            Price = 5885.47m,
                            Title = "Incredible Rubber Pizza"
                        },
                        new
                        {
                            Id = 69,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3568),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 20.12m,
                            IsDeleted = true,
                            Price = 5712.79m,
                            Title = "Intelligent Granite Pizza"
                        },
                        new
                        {
                            Id = 70,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 26, 1, 6, 21, 524, DateTimeKind.Local).AddTicks(3602),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 12.78m,
                            IsDeleted = true,
                            Price = 7379.81m,
                            Title = "Practical Metal Tuna"
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpireTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Detail", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Product", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
