// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionArchitectureWebAPI.Persistance.Context;

#nullable disable

namespace OnionArchitectureWebAPI.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118114429_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(7221),
                            IsDeleted = false,
                            Name = "Özdoğan, Koçoğlu and Paksüt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(7360),
                            IsDeleted = false,
                            Name = "Akan Group"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(7447),
                            IsDeleted = false,
                            Name = "Çağıran and Sons"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(7534),
                            IsDeleted = false,
                            Name = "Akyürek Inc"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(7660),
                            IsDeleted = false,
                            Name = "Oraloğlu, Kasapoğlu and Topaloğlu"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(7734),
                            IsDeleted = false,
                            Name = "Kıraç  - Tütüncü"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(7821),
                            IsDeleted = false,
                            Name = "Karabulut LLC"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(7899),
                            IsDeleted = false,
                            Name = "Yetkiner - Atan"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(8017),
                            IsDeleted = false,
                            Name = "Öymen, Koyuncu and Sezek"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(8094),
                            IsDeleted = false,
                            Name = "Bakırcıoğlu and Sons"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(8240),
                            IsDeleted = true,
                            Name = "Koçyiğit Group"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(8392),
                            IsDeleted = true,
                            Name = "Erginsoy, Solmaz and Alpuğan"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(8479),
                            IsDeleted = true,
                            Name = "Okur and Sons"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(8561),
                            IsDeleted = true,
                            Name = "Ekici LLC"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 693, DateTimeKind.Local).AddTicks(8645),
                            IsDeleted = true,
                            Name = "Numanoğlu - Sandalcı"
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priorty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 694, DateTimeKind.Local).AddTicks(2158),
                            IsDeleted = false,
                            Name = "Elektrik",
                            ParentId = 0,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 694, DateTimeKind.Local).AddTicks(2164),
                            IsDeleted = false,
                            Name = "Moda",
                            ParentId = 0,
                            Priorty = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 694, DateTimeKind.Local).AddTicks(2165),
                            IsDeleted = false,
                            Name = "Bilgisayar",
                            ParentId = 1,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 694, DateTimeKind.Local).AddTicks(2166),
                            IsDeleted = false,
                            Name = "Kadın",
                            ParentId = 2,
                            Priorty = 1
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(23),
                            Description = "Aliquam beğendim masanın doğru alias.",
                            IsDeleted = false,
                            Title = "Koşuyorlar."
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(73),
                            Description = "Eos sit yazın eum alias.",
                            IsDeleted = false,
                            Title = "Aut."
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(108),
                            Description = "Nihil amet orta göze nihil.",
                            IsDeleted = false,
                            Title = "Değirmeni."
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(141),
                            Description = "Adresini cesurca tempora consequuntur qui.",
                            IsDeleted = false,
                            Title = "Eve."
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(171),
                            Description = "Eve düşünüyor kulu aut biber.",
                            IsDeleted = false,
                            Title = "Odio."
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(213),
                            Description = "Autem lakin velit quia layıkıyla.",
                            IsDeleted = false,
                            Title = "Quis."
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(246),
                            Description = "Voluptatem quia qui ekşili voluptas.",
                            IsDeleted = false,
                            Title = "Ex."
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(275),
                            Description = "Çakıl dolor ekşili ipsa de.",
                            IsDeleted = false,
                            Title = "Numquam."
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(305),
                            Description = "Gitti balıkhaneye teldeki qui aut.",
                            IsDeleted = false,
                            Title = "Tv."
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(336),
                            Description = "Mi enim ekşili doloremque ut.",
                            IsDeleted = false,
                            Title = "Autem."
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(367),
                            Description = "Quam tempora quasi eos teldeki.",
                            IsDeleted = false,
                            Title = "Velit."
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(398),
                            Description = "Sunt quia öyle sıla perferendis.",
                            IsDeleted = false,
                            Title = "İçin."
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(432),
                            Description = "Sit dolorem enim sunt sokaklarda.",
                            IsDeleted = false,
                            Title = "Architecto."
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(465),
                            Description = "Ut kalemi vitae quasi sevindi.",
                            IsDeleted = false,
                            Title = "Totam."
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(494),
                            Description = "Nisi beğendim reprehenderit iusto dolorem.",
                            IsDeleted = false,
                            Title = "İpsa."
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(521),
                            Description = "Masanın nisi qui quasi ea.",
                            IsDeleted = false,
                            Title = "Değerli."
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(789),
                            Description = "Amet exercitationem voluptatem autem kapının.",
                            IsDeleted = false,
                            Title = "Çobanın."
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(819),
                            Description = "İçin ipsum sequi sayfası ipsa.",
                            IsDeleted = false,
                            Title = "Aliquid."
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(846),
                            Description = "Sokaklarda layıkıyla sequi accusantium aut.",
                            IsDeleted = false,
                            Title = "Quia."
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(873),
                            Description = "Ama cesurca ex sed exercitationem.",
                            IsDeleted = false,
                            Title = "Anlamsız."
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(916),
                            Description = "Eve çarpan gazete consequatur umut.",
                            IsDeleted = true,
                            Title = "Filmini."
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(943),
                            Description = "Nisi koşuyorlar kulu cesurca enim.",
                            IsDeleted = true,
                            Title = "Ut."
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(971),
                            Description = "Adipisci cesurca aperiam eaque doloremque.",
                            IsDeleted = true,
                            Title = "Ullam."
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(999),
                            Description = "Değerli ullam telefonu tv ve.",
                            IsDeleted = true,
                            Title = "Quae."
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 696, DateTimeKind.Local).AddTicks(1027),
                            Description = "Veritatis gül kalemi biber oldular.",
                            IsDeleted = true,
                            Title = "Quia."
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9199),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 18.08m,
                            IsDeleted = false,
                            Price = 6598.73m,
                            Title = "Handmade Plastic Shoes"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9257),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 45.56m,
                            IsDeleted = false,
                            Price = 6408.13m,
                            Title = "Practical Fresh Shirt"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9291),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 34.70m,
                            IsDeleted = false,
                            Price = 8987.84m,
                            Title = "Small Metal Hat"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9324),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 4.05m,
                            IsDeleted = false,
                            Price = 9167.87m,
                            Title = "Small Frozen Keyboard"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9354),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 26.71m,
                            IsDeleted = false,
                            Price = 9230.04m,
                            Title = "Rustic Metal Keyboard"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9393),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 25.43m,
                            IsDeleted = false,
                            Price = 1708.80m,
                            Title = "Rustic Metal Ball"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9428),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 16.83m,
                            IsDeleted = false,
                            Price = 3075.47m,
                            Title = "Refined Metal Mouse"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9457),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 11.35m,
                            IsDeleted = false,
                            Price = 3692.80m,
                            Title = "Sleek Cotton Towels"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9485),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 48.27m,
                            IsDeleted = false,
                            Price = 4613.38m,
                            Title = "Gorgeous Wooden Keyboard"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9517),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 25.03m,
                            IsDeleted = false,
                            Price = 3959.07m,
                            Title = "Incredible Cotton Sausages"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9548),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 22.25m,
                            IsDeleted = false,
                            Price = 3391.63m,
                            Title = "Tasty Rubber Bike"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9577),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 10.33m,
                            IsDeleted = false,
                            Price = 3620.59m,
                            Title = "Fantastic Frozen Tuna"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9605),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 43.64m,
                            IsDeleted = false,
                            Price = 4187.19m,
                            Title = "Tasty Concrete Pizza"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9634),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 18.59m,
                            IsDeleted = false,
                            Price = 8794.50m,
                            Title = "Unbranded Metal Fish"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9670),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 48.93m,
                            IsDeleted = false,
                            Price = 8920.56m,
                            Title = "Incredible Metal Table"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9697),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 46.81m,
                            IsDeleted = false,
                            Price = 9639.73m,
                            Title = "Sleek Steel Chair"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9727),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 24.16m,
                            IsDeleted = false,
                            Price = 6005.93m,
                            Title = "Generic Granite Keyboard"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9754),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 10.30m,
                            IsDeleted = false,
                            Price = 5117.98m,
                            Title = "Sleek Metal Shirt"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9783),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 44.70m,
                            IsDeleted = false,
                            Price = 6872.43m,
                            Title = "Sleek Frozen Computer"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9811),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 22.37m,
                            IsDeleted = false,
                            Price = 7871.19m,
                            Title = "Incredible Frozen Mouse"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9839),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 10.19m,
                            IsDeleted = false,
                            Price = 3881.20m,
                            Title = "Handcrafted Metal Ball"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9868),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 39.36m,
                            IsDeleted = false,
                            Price = 5017.54m,
                            Title = "Licensed Wooden Salad"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9896),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 6.40m,
                            IsDeleted = false,
                            Price = 9050.48m,
                            Title = "Handcrafted Plastic Bacon"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9932),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 45.06m,
                            IsDeleted = false,
                            Price = 8076.71m,
                            Title = "Incredible Metal Chips"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9961),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 9.30m,
                            IsDeleted = false,
                            Price = 6742.50m,
                            Title = "Handcrafted Metal Fish"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 698, DateTimeKind.Local).AddTicks(9988),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 35.09m,
                            IsDeleted = false,
                            Price = 4657.79m,
                            Title = "Practical Fresh Keyboard"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(17),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 4.81m,
                            IsDeleted = false,
                            Price = 898.56m,
                            Title = "Handcrafted Cotton Towels"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(45),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 29.80m,
                            IsDeleted = false,
                            Price = 2512.37m,
                            Title = "Sleek Wooden Pizza"
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(72),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 39.84m,
                            IsDeleted = false,
                            Price = 1604.97m,
                            Title = "Tasty Wooden Chair"
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(100),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 13.46m,
                            IsDeleted = false,
                            Price = 5983.61m,
                            Title = "Rustic Steel Keyboard"
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(129),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 0.49m,
                            IsDeleted = false,
                            Price = 677.84m,
                            Title = "Ergonomic Wooden Cheese"
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(157),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 1.73m,
                            IsDeleted = false,
                            Price = 1468.68m,
                            Title = "Fantastic Fresh Pants"
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(184),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 31.77m,
                            IsDeleted = false,
                            Price = 3949.97m,
                            Title = "Handmade Plastic Computer"
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(219),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 35.65m,
                            IsDeleted = false,
                            Price = 9180.43m,
                            Title = "Licensed Frozen Chicken"
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(247),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 41.69m,
                            IsDeleted = false,
                            Price = 3907.91m,
                            Title = "Fantastic Rubber Tuna"
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(276),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 0.64m,
                            IsDeleted = false,
                            Price = 6369.27m,
                            Title = "Intelligent Soft Pants"
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(305),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 35.12m,
                            IsDeleted = false,
                            Price = 8552.24m,
                            Title = "Rustic Fresh Ball"
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(333),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 12.72m,
                            IsDeleted = false,
                            Price = 7627.42m,
                            Title = "Small Soft Ball"
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(361),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 29.31m,
                            IsDeleted = false,
                            Price = 9247.58m,
                            Title = "Handmade Granite Chicken"
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(388),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 42.39m,
                            IsDeleted = false,
                            Price = 5051.78m,
                            Title = "Gorgeous Concrete Computer"
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(417),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 42.48m,
                            IsDeleted = false,
                            Price = 1008.33m,
                            Title = "Unbranded Fresh Soap"
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(445),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 43.43m,
                            IsDeleted = false,
                            Price = 271.38m,
                            Title = "Unbranded Granite Bacon"
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(481),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 38.88m,
                            IsDeleted = false,
                            Price = 5670.27m,
                            Title = "Ergonomic Wooden Chips"
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(509),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 40.40m,
                            IsDeleted = false,
                            Price = 3487.04m,
                            Title = "Handcrafted Fresh Mouse"
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(538),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 13.23m,
                            IsDeleted = false,
                            Price = 6049.23m,
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(566),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 3.17m,
                            IsDeleted = false,
                            Price = 2318.35m,
                            Title = "Unbranded Metal Shirt"
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(595),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 41.50m,
                            IsDeleted = false,
                            Price = 159.51m,
                            Title = "Ergonomic Metal Bacon"
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(623),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 29.99m,
                            IsDeleted = false,
                            Price = 4128.22m,
                            Title = "Awesome Soft Hat"
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(651),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 7.36m,
                            IsDeleted = false,
                            Price = 6469.08m,
                            Title = "Incredible Metal Table"
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(678),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 34.64m,
                            IsDeleted = false,
                            Price = 9914.63m,
                            Title = "Small Frozen Chicken"
                        },
                        new
                        {
                            Id = 51,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(716),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 11.74m,
                            IsDeleted = true,
                            Price = 3701.64m,
                            Title = "Practical Cotton Hat"
                        },
                        new
                        {
                            Id = 52,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(752),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 18.41m,
                            IsDeleted = true,
                            Price = 7072.32m,
                            Title = "Fantastic Rubber Mouse"
                        },
                        new
                        {
                            Id = 53,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(781),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 0.57m,
                            IsDeleted = true,
                            Price = 9888.97m,
                            Title = "Rustic Concrete Salad"
                        },
                        new
                        {
                            Id = 54,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(809),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 9.70m,
                            IsDeleted = true,
                            Price = 7499.12m,
                            Title = "Ergonomic Steel Chicken"
                        },
                        new
                        {
                            Id = 55,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(838),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 18.41m,
                            IsDeleted = true,
                            Price = 9004.66m,
                            Title = "Fantastic Wooden Mouse"
                        },
                        new
                        {
                            Id = 56,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(865),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 26.75m,
                            IsDeleted = true,
                            Price = 6155.31m,
                            Title = "Sleek Frozen Salad"
                        },
                        new
                        {
                            Id = 57,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(893),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 26.61m,
                            IsDeleted = true,
                            Price = 2744.71m,
                            Title = "Generic Plastic Chips"
                        },
                        new
                        {
                            Id = 58,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(922),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 13.27m,
                            IsDeleted = true,
                            Price = 8291.17m,
                            Title = "Ergonomic Wooden Car"
                        },
                        new
                        {
                            Id = 59,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(950),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 7.49m,
                            IsDeleted = true,
                            Price = 1980.75m,
                            Title = "Generic Wooden Towels"
                        },
                        new
                        {
                            Id = 60,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(979),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 0.76m,
                            IsDeleted = true,
                            Price = 7987.58m,
                            Title = "Handcrafted Plastic Shoes"
                        },
                        new
                        {
                            Id = 61,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1015),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 3.09m,
                            IsDeleted = true,
                            Price = 5234.82m,
                            Title = "Handcrafted Wooden Shirt"
                        },
                        new
                        {
                            Id = 62,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1043),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 11.49m,
                            IsDeleted = true,
                            Price = 4402.01m,
                            Title = "Licensed Plastic Gloves"
                        },
                        new
                        {
                            Id = 63,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1070),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 18.24m,
                            IsDeleted = true,
                            Price = 2359.64m,
                            Title = "Intelligent Fresh Table"
                        },
                        new
                        {
                            Id = 64,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1098),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 23.23m,
                            IsDeleted = true,
                            Price = 8980.05m,
                            Title = "Licensed Steel Shoes"
                        },
                        new
                        {
                            Id = 65,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1126),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 37.58m,
                            IsDeleted = true,
                            Price = 729.88m,
                            Title = "Handcrafted Granite Towels"
                        },
                        new
                        {
                            Id = 66,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1154),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 34.27m,
                            IsDeleted = true,
                            Price = 3134.66m,
                            Title = "Licensed Frozen Soap"
                        },
                        new
                        {
                            Id = 67,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1182),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 30.28m,
                            IsDeleted = true,
                            Price = 4256.34m,
                            Title = "Handmade Steel Towels"
                        },
                        new
                        {
                            Id = 68,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1210),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 14.25m,
                            IsDeleted = true,
                            Price = 2700.21m,
                            Title = "Generic Plastic Ball"
                        },
                        new
                        {
                            Id = 69,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1238),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 0.97m,
                            IsDeleted = true,
                            Price = 8278.81m,
                            Title = "Refined Wooden Chair"
                        },
                        new
                        {
                            Id = 70,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 11, 18, 14, 44, 28, 699, DateTimeKind.Local).AddTicks(1274),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 27.06m,
                            IsDeleted = true,
                            Price = 6222.05m,
                            Title = "Rustic Wooden Chicken"
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Detail", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Product", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
