// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionArchitectureWebAPI.Persistance.Context;

#nullable disable

namespace OnionArchitectureWebAPI.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251021131430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(4592),
                            IsDeleted = false,
                            Name = "Limoncuoğlu, Demirbaş and Aşıkoğlu"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(4777),
                            IsDeleted = false,
                            Name = "Erez and Sons"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(4886),
                            IsDeleted = false,
                            Name = "Çetin - Doğan "
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(4993),
                            IsDeleted = false,
                            Name = "Atan - Körmükçü"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(5147),
                            IsDeleted = false,
                            Name = "Yalçın, Arıcan and Aclan"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(5251),
                            IsDeleted = false,
                            Name = "Ertepınar LLC"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(5357),
                            IsDeleted = false,
                            Name = "Ayaydın - Yalçın"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(5498),
                            IsDeleted = false,
                            Name = "Egeli, Bademci and Özberk"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(5601),
                            IsDeleted = false,
                            Name = "Ertepınar - Kutlay"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(5755),
                            IsDeleted = false,
                            Name = "Alnıaçık, Beşok and Akay"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(6010),
                            IsDeleted = true,
                            Name = "Kurutluoğlu, Çatalbaş and Keseroğlu"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(6162),
                            IsDeleted = true,
                            Name = "Tuğluk, Hakyemez and Çağıran"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(6310),
                            IsDeleted = true,
                            Name = "Yazıcı, Abadan and Dağlaroğlu"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(6416),
                            IsDeleted = true,
                            Name = "Köybaşı and Sons"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 971, DateTimeKind.Local).AddTicks(6527),
                            IsDeleted = true,
                            Name = "Günday - Önür"
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priorty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 972, DateTimeKind.Local).AddTicks(473),
                            IsDeleted = false,
                            Name = "Elektrik",
                            ParentId = 0,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 972, DateTimeKind.Local).AddTicks(479),
                            IsDeleted = false,
                            Name = "Moda",
                            ParentId = 0,
                            Priorty = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 972, DateTimeKind.Local).AddTicks(481),
                            IsDeleted = false,
                            Name = "Bilgisayar",
                            ParentId = 1,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 972, DateTimeKind.Local).AddTicks(482),
                            IsDeleted = false,
                            Name = "kadın",
                            ParentId = 2,
                            Priorty = 1
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3070),
                            Description = "Masanın kulu ex koştum voluptate.",
                            IsDeleted = false,
                            Title = "Eve."
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3123),
                            Description = "Voluptatem kulu ki consequatur yaptı.",
                            IsDeleted = false,
                            Title = "Minima."
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3165),
                            Description = "Laudantium sinema değirmeni koşuyorlar ekşili.",
                            IsDeleted = false,
                            Title = "Cesurca."
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3207),
                            Description = "Quia yapacakmış layıkıyla non domates.",
                            IsDeleted = false,
                            Title = "Non."
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3246),
                            Description = "Consequatur lakin sed koyun quis.",
                            IsDeleted = false,
                            Title = "Değerli."
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3287),
                            Description = "İçin aperiam dolayı de odio.",
                            IsDeleted = false,
                            Title = "Molestiae."
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3332),
                            Description = "Vitae rem çorba dicta orta.",
                            IsDeleted = false,
                            Title = "Bilgisayarı."
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3370),
                            Description = "Balıkhaneye cezbelendi sıfat ullam totam.",
                            IsDeleted = false,
                            Title = "Voluptatem."
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3407),
                            Description = "Yazın ve karşıdakine yapacakmış kulu.",
                            IsDeleted = false,
                            Title = "Quis."
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3452),
                            Description = "Koşuyorlar sinema rem iure et.",
                            IsDeleted = false,
                            Title = "Açılmadan."
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3488),
                            Description = "Aperiam kalemi consequatur çünkü bahar.",
                            IsDeleted = false,
                            Title = "Masanın."
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3524),
                            Description = "Biber tempora sıla dergi ut.",
                            IsDeleted = false,
                            Title = "Düşünüyor."
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3562),
                            Description = "Aliquam açılmadan eius ratione ama.",
                            IsDeleted = false,
                            Title = "Quia."
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3599),
                            Description = "Otobüs orta aliquid beatae oldular.",
                            IsDeleted = false,
                            Title = "Layıkıyla."
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3639),
                            Description = "Patlıcan ducimus quaerat ducimus bilgiyasayarı.",
                            IsDeleted = false,
                            Title = "Değerli."
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3672),
                            Description = "Değirmeni reprehenderit sevindi eius ipsam.",
                            IsDeleted = false,
                            Title = "Domates."
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3709),
                            Description = "Makinesi eaque non nisi sokaklarda.",
                            IsDeleted = false,
                            Title = "Sarmal."
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3742),
                            Description = "Un gazete mutlu dolor çakıl.",
                            IsDeleted = false,
                            Title = "Sarmal."
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3778),
                            Description = "Işık quasi magni nesciunt et.",
                            IsDeleted = false,
                            Title = "Beğendim."
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3909),
                            Description = "Numquam commodi salladı oldular explicabo.",
                            IsDeleted = false,
                            Title = "Bilgisayarı."
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3960),
                            Description = "Nisi accusantium in quam açılmadan.",
                            IsDeleted = true,
                            Title = "Voluptatem."
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(3995),
                            Description = "Çakıl kutusu sunt kutusu numquam.",
                            IsDeleted = true,
                            Title = "Çakıl."
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(4028),
                            Description = "Ut kapının göze salladı veniam.",
                            IsDeleted = true,
                            Title = "Quis."
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(4062),
                            Description = "Sıla gülüyorum mıknatıslı gidecekmiş labore.",
                            IsDeleted = true,
                            Title = "İure."
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 974, DateTimeKind.Local).AddTicks(4097),
                            Description = "Salladı magnam qui ullam ki.",
                            IsDeleted = true,
                            Title = "Consequatur."
                        });
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6248),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 222.00m,
                            IsDeleted = false,
                            Price = 6447.45m,
                            Title = "Unbranded Granite Salad"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6309),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 284.16m,
                            IsDeleted = false,
                            Price = 3414.88m,
                            Title = "Fantastic Plastic Towels"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6365),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 178.03m,
                            IsDeleted = false,
                            Price = 2208.81m,
                            Title = "Handcrafted Cotton Hat"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6408),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 223.58m,
                            IsDeleted = false,
                            Price = 803.92m,
                            Title = "Incredible Steel Gloves"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6445),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 232.25m,
                            IsDeleted = false,
                            Price = 6730.26m,
                            Title = "Practical Cotton Shirt"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6487),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 0.02m,
                            IsDeleted = false,
                            Price = 5596.47m,
                            Title = "Gorgeous Granite Towels"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6528),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 210.02m,
                            IsDeleted = false,
                            Price = 5676.46m,
                            Title = "Intelligent Metal Chicken"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6565),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 167.79m,
                            IsDeleted = false,
                            Price = 9756.42m,
                            Title = "Sleek Concrete Pizza"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6601),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 57.61m,
                            IsDeleted = false,
                            Price = 5423.12m,
                            Title = "Ergonomic Wooden Towels"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6641),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 279.35m,
                            IsDeleted = false,
                            Price = 3120.59m,
                            Title = "Handcrafted Granite Table"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6677),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 257.86m,
                            IsDeleted = false,
                            Price = 5361.71m,
                            Title = "Rustic Cotton Car"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6726),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 106.72m,
                            IsDeleted = false,
                            Price = 8480.22m,
                            Title = "Small Wooden Cheese"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6763),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 254.39m,
                            IsDeleted = false,
                            Price = 8286.44m,
                            Title = "Incredible Concrete Hat"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6799),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 245.08m,
                            IsDeleted = false,
                            Price = 8598.08m,
                            Title = "Awesome Cotton Shirt"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6837),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 59.40m,
                            IsDeleted = false,
                            Price = 6869.77m,
                            Title = "Unbranded Fresh Car"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6873),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 93.49m,
                            IsDeleted = false,
                            Price = 8569.61m,
                            Title = "Sleek Cotton Salad"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6909),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 161.08m,
                            IsDeleted = false,
                            Price = 7941.23m,
                            Title = "Small Rubber Shoes"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6946),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 115.68m,
                            IsDeleted = false,
                            Price = 6150.66m,
                            Title = "Unbranded Plastic Chips"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(6982),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 61.53m,
                            IsDeleted = false,
                            Price = 5956.66m,
                            Title = "Fantastic Rubber Shirt"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7019),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 155.87m,
                            IsDeleted = false,
                            Price = 9370.81m,
                            Title = "Ergonomic Plastic Tuna"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7070),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 138.83m,
                            IsDeleted = false,
                            Price = 5677.67m,
                            Title = "Incredible Fresh Bacon"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7107),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 40.42m,
                            IsDeleted = false,
                            Price = 8476.50m,
                            Title = "Small Cotton Shoes"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7143),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 127.29m,
                            IsDeleted = false,
                            Price = 7231.16m,
                            Title = "Intelligent Frozen Tuna"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7179),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 79.85m,
                            IsDeleted = false,
                            Price = 1322.92m,
                            Title = "Unbranded Steel Keyboard"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7215),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 165.53m,
                            IsDeleted = false,
                            Price = 4765.75m,
                            Title = "Tasty Concrete Gloves"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7251),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 205.29m,
                            IsDeleted = false,
                            Price = 5948.63m,
                            Title = "Handmade Concrete Chips"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7286),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 64.40m,
                            IsDeleted = false,
                            Price = 7675.23m,
                            Title = "Awesome Frozen Table"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7322),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 128.03m,
                            IsDeleted = false,
                            Price = 6923.16m,
                            Title = "Unbranded Granite Fish"
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7358),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 83.65m,
                            IsDeleted = false,
                            Price = 5633.38m,
                            Title = "Ergonomic Metal Cheese"
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7394),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 98.79m,
                            IsDeleted = false,
                            Price = 7519.87m,
                            Title = "Small Soft Pants"
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7438),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 287.63m,
                            IsDeleted = false,
                            Price = 8685.24m,
                            Title = "Rustic Granite Shirt"
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7474),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 173.12m,
                            IsDeleted = false,
                            Price = 5866.39m,
                            Title = "Handcrafted Metal Tuna"
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7510),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 199.38m,
                            IsDeleted = false,
                            Price = 2492.66m,
                            Title = "Rustic Cotton Cheese"
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7545),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 199.07m,
                            IsDeleted = false,
                            Price = 3889.14m,
                            Title = "Handmade Cotton Computer"
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7582),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 186.48m,
                            IsDeleted = false,
                            Price = 8097.51m,
                            Title = "Generic Plastic Chips"
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7615),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 36.03m,
                            IsDeleted = false,
                            Price = 556.20m,
                            Title = "Licensed Rubber Hat"
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7650),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 251.50m,
                            IsDeleted = false,
                            Price = 7780.64m,
                            Title = "Ergonomic Frozen Towels"
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7685),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 101.09m,
                            IsDeleted = false,
                            Price = 5385.25m,
                            Title = "Intelligent Rubber Hat"
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7720),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 58.15m,
                            IsDeleted = false,
                            Price = 2108.10m,
                            Title = "Intelligent Frozen Table"
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7760),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 33.98m,
                            IsDeleted = false,
                            Price = 3604.18m,
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 9,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7794),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 100.99m,
                            IsDeleted = false,
                            Price = 4764.48m,
                            Title = "Tasty Plastic Shirt"
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7828),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 204.54m,
                            IsDeleted = false,
                            Price = 8589.72m,
                            Title = "Small Frozen Shoes"
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7862),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 284.15m,
                            IsDeleted = false,
                            Price = 1075.02m,
                            Title = "Rustic Granite Bacon"
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7895),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 168.36m,
                            IsDeleted = false,
                            Price = 3742.22m,
                            Title = "Small Concrete Salad"
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7930),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 120.88m,
                            IsDeleted = false,
                            Price = 8002.25m,
                            Title = "Small Wooden Mouse"
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7964),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 285.04m,
                            IsDeleted = false,
                            Price = 2786.21m,
                            Title = "Fantastic Soft Shoes"
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(7997),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 177.82m,
                            IsDeleted = false,
                            Price = 629.54m,
                            Title = "Handmade Steel Chips"
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8030),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 133.92m,
                            IsDeleted = false,
                            Price = 5215.42m,
                            Title = "Small Granite Car"
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8072),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 121.99m,
                            IsDeleted = false,
                            Price = 3017.52m,
                            Title = "Sleek Concrete Towels"
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8107),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 185.04m,
                            IsDeleted = false,
                            Price = 2374.52m,
                            Title = "Practical Plastic Mouse"
                        },
                        new
                        {
                            Id = 51,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8156),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 292.79m,
                            IsDeleted = true,
                            Price = 2106.73m,
                            Title = "Gorgeous Metal Shoes"
                        },
                        new
                        {
                            Id = 52,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8190),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 114.49m,
                            IsDeleted = true,
                            Price = 819.03m,
                            Title = "Fantastic Metal Computer"
                        },
                        new
                        {
                            Id = 53,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8225),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 5.00m,
                            IsDeleted = true,
                            Price = 5109.09m,
                            Title = "Fantastic Soft Pizza"
                        },
                        new
                        {
                            Id = 54,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8260),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 62.92m,
                            IsDeleted = true,
                            Price = 8319.55m,
                            Title = "Handmade Frozen Bike"
                        },
                        new
                        {
                            Id = 55,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8294),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 162.38m,
                            IsDeleted = true,
                            Price = 8653.88m,
                            Title = "Fantastic Plastic Ball"
                        },
                        new
                        {
                            Id = 56,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8328),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 269.14m,
                            IsDeleted = true,
                            Price = 8298.83m,
                            Title = "Handcrafted Plastic Tuna"
                        },
                        new
                        {
                            Id = 57,
                            BrandId = 10,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8361),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 123.14m,
                            IsDeleted = true,
                            Price = 8777.50m,
                            Title = "Rustic Metal Towels"
                        },
                        new
                        {
                            Id = 58,
                            BrandId = 8,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8412),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 162.64m,
                            IsDeleted = true,
                            Price = 5790.14m,
                            Title = "Awesome Granite Shoes"
                        },
                        new
                        {
                            Id = 59,
                            BrandId = 3,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8446),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 37.92m,
                            IsDeleted = true,
                            Price = 1523.31m,
                            Title = "Licensed Steel Computer"
                        },
                        new
                        {
                            Id = 60,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8480),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Discount = 147.75m,
                            IsDeleted = true,
                            Price = 9068.48m,
                            Title = "Intelligent Soft Chair"
                        },
                        new
                        {
                            Id = 61,
                            BrandId = 7,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8514),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 115.13m,
                            IsDeleted = true,
                            Price = 5098.61m,
                            Title = "Ergonomic Steel Gloves"
                        },
                        new
                        {
                            Id = 62,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8548),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 192.07m,
                            IsDeleted = true,
                            Price = 4548.96m,
                            Title = "Sleek Soft Hat"
                        },
                        new
                        {
                            Id = 63,
                            BrandId = 1,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8582),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 53.89m,
                            IsDeleted = true,
                            Price = 417.44m,
                            Title = "Intelligent Rubber Sausages"
                        },
                        new
                        {
                            Id = 64,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8616),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 10.00m,
                            IsDeleted = true,
                            Price = 5181.58m,
                            Title = "Licensed Cotton Gloves"
                        },
                        new
                        {
                            Id = 65,
                            BrandId = 6,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8650),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 210.38m,
                            IsDeleted = true,
                            Price = 1815.39m,
                            Title = "Handcrafted Granite Ball"
                        },
                        new
                        {
                            Id = 66,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8684),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 121.81m,
                            IsDeleted = true,
                            Price = 336.67m,
                            Title = "Handcrafted Fresh Shoes"
                        },
                        new
                        {
                            Id = 67,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8719),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 99.47m,
                            IsDeleted = true,
                            Price = 4483.32m,
                            Title = "Intelligent Soft Tuna"
                        },
                        new
                        {
                            Id = 68,
                            BrandId = 4,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8761),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 130.60m,
                            IsDeleted = true,
                            Price = 9077.86m,
                            Title = "Ergonomic Rubber Towels"
                        },
                        new
                        {
                            Id = 69,
                            BrandId = 2,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8794),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Discount = 86.93m,
                            IsDeleted = true,
                            Price = 1056.97m,
                            Title = "Tasty Fresh Mouse"
                        },
                        new
                        {
                            Id = 70,
                            BrandId = 5,
                            CreatedDate = new DateTime(2025, 10, 21, 16, 14, 29, 976, DateTimeKind.Local).AddTicks(8828),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Discount = 20.66m,
                            IsDeleted = true,
                            Price = 6155.87m,
                            Title = "Gorgeous Soft Chips"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Detail", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Product", b =>
                {
                    b.HasOne("OnionArchitectureWebAPI.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnionArchitectureWebAPI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
